[project]
name = "ragproductionapp"
version = "0.1.0"
description = "AI PDF RAG Assistant"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "streamlit>=1.49.1",
    "python-dotenv>=1.1.1",
    "qdrant-client>=1.15.1",
    "sentence-transformers>=3.0.1",
    "torch>=2.7.0",
    "llama-index-core>=0.14.0",
    "llama-index-readers-file>=0.5.4",
    "groq>=0.31.0",
]